project_id = "ceknjgwzxexxzckcqjmq"

[functions.manage-users]
verify_jwt = false

[functions.admin-update]
verify_jwt = false

[functions.scrape-tiktok]
verify_jwt = false

[functions.calendly-webhook]
verify_jwt = false

[functions.connect-calendly]
verify_jwt = false

[functions.complete-onboarding]
verify_jwt = false