project_id = "ceknjgwzxexxzckcqjmq"

[functions.manage-users]
verify_jwt = false

[functions.admin-update]
verify_jwt = false

[functions.scrape-tiktok]
verify_jwt = false

[functions.complete-onboarding]
verify_jwt = false

[functions.generate-alerts]
verify_jwt = false

[functions.regenerate-client-payments]
verify_jwt = false

[functions.run-finance-jobs]
verify_jwt = false