// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://ceknjgwzxexxzckcqjmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNla25qZ3d6eGV4eHpja2Nxam1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyNzAyMDcsImV4cCI6MjA4Nzg0NjIwN30.ugfGWCmG46HV_buJENCwN_wSCKcH6XoDVXY-pLn9ekQ";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});